### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by devoidfury** [cohix/Imperium#1]
Installation for me failed -- cloned the repo, moved into the src/ directory, and ran npm install.

My guess is that NPM is expecting a semver-compatible version number (x.x.x) but I'm not 100% sure.

```
$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid version: "0.1"
npm ERR!     at Object.module.exports.fixVersionField (c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\
normalize-package-data\lib\fixer.js:185:13)
npm ERR!     at c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js
:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\n
ormalize.js:28:15)
npm ERR!     at final (c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:328:33)
npm ERR!     at then (c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:126:33)
npm ERR!     at c:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:302:48
npm ERR!     at fs.js:207:20
npm ERR!     at OpenReq.Req.done (c:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:144:5)
npm ERR!     at OpenReq.done (c:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:64:22)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\dev-new\projects\test_imp\Imperium\src
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Users\dev-new\projects\test_imp\Imperium\src\npm-debug.log
npm ERR! not ok code 0
```

**Comment by cohix** [comment]
Yep, that was my bad, I edited package.json in the github editor without thinking. The fix is already in the v0_2 branch. You can do git fetch && git checkout v0_2, or wait until tonight (11pm EST) when I merge it into master.

**Comment by cohix** [comment]
A bit late, but the fix has been merged into master. Cheers.
